### ISSUE TITLE
Infinite reload due to authorization failed with public links

### ISSUE THREAD

**Issue by stefan2503** [Patt92/Workin2Gether#7] opened 2016-04-01 15:01 UTC
Hi,

I had to disable this app since it created an infinite reload loop on a public shared folder.
If the user is not logged in it will set the incognito modus to true (this happens).
Later when your app starts it checks the log on which then fails incognito modus=false.
This caues a json reply with authorization failed (401).
If I disable this app everything works fine.
owncloud 9.0.0 app version 0.8.2.6-

**Comment by Patt92** [comment] 2016-04-05 13:56
Hello,

sorry to hear about that. There was a huge change in OC9 concerning the permission. The redirect gets caused by the checkLoggedIn, which I had to add for getting my app approved.

To fix it, change the file /appinfo/app.php, replace the launch method with the following:

 public static function launch()
        {
                if(\OC_User::isLoggedIn())
                {
                        \OCP\Util::addScript( self::name, 'workin2gether');

```
                    \OCP\Util::addstyle( self::name, 'styles');

                    \OCP\App::registerAdmin(self::name, 'admin');
            }
    }
```

It will prevent the load of the app, if you are not logged in.

Cheers,

Patrick

**Comment by stefan2503** [comment] 2016-04-06 07:37
Thanks for your reply. Unfortunately I do not have a test system available to try this out. I think I leave the app disabled for now to be on the safe side. Its a production system after all.

**Comment by Patt92** [comment] 2016-04-06 07:40
It was caused by a policy, which needs authenticated users. The app is now completely disabled for public users. I will push the update, once the OC appstore works again. The upload is not working at the moment. I've tested it on my test system, there were the reloads too. Now not any more.

**Comment by Patt92** [comment] 2016-04-18 08:10
Fix has been pushed last week. The issue won't appear with version 0.8.3.0

**Closed as completed by Patt92** 2016-04-18 08:10 UTC
